$on_ac_power = systemd-ac-power
$kbd_backlight = tpacpi::kbd_backlight
$min1   = 60
$min2   = 120
$min2_5 = 150
$min5   = 300
$min10  = 600
$min20  = 1200


general {
    lock_cmd = pidof hyprlock || hyprlock                                    # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                 # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

# Battery: dim screen after 2mins idle
listener {
    timeout     = $min2                                         # 2min
    on-timeout  = $on_ac_power || brightnessctl -s set 100      # dim backlight to 100 if AC off
    on-resume   = brightnessctl -r                              # restore monitor backlight
}

# Battery: turn keyboard off after 2 mins idle
listener { 
    timeout     = $min2                                                       # 2min.
    on-timeout  = $on_ac_power || brightnessctl -sd $kbd_backlight set 0      # turn off keyboard backlight if AC off
    on-resume   = $on_ac_power || brightnessctl -r $kbd_backlight             # restore keyboard backlight.
}

# Battery: lock session after 2.5 mins idle
listener {
    timeout     = $min2_5                                    # 2.5min
    on-timeout  = $on_ac_power || loginctl lock-session      # lock screen when timeout has passed
}

# Battery: turn off display after 5 mins idle
listener {
    timeout     = $min5                                                                                          # 5.5min
    on-timeout  = $on_ac_power || hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                         # screen off when timeout has passed
    on-resume   = $on_ac_power || hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r      # screen on when activity is detected after timeout has fired.
}

# Battery: turn on
listener {
    timeout     = $min20                                 # 30min
    on-timeout  = $on_ac_power || systemctl suspend      # suspend pc
}
