$on_ac_power = systemd-ac-power
$kbd_backlight = tpacpi::kbd_backlight
$lock_screen = hyprlock
$min3   = 180
$min4   = 240
$min5   = 300
$min10  = 600
$min20  = 1200


general {
    lock_cmd = pidof $lock_screen || $lock_screen                                    # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                 # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

# Dim screen after 3 mins idle
listener {
    timeout     = $min3                         
    on-timeout  = brightnessctl -s set 100      # dim screen to 100
    on-resume   = brightnessctl -r              # restore monitor brightness
}

# Turn keyboard light off after 3 mins idle
listener { 
    timeout     = $min3                                       
    on-timeout  = brightnessctl -sd $kbd_backlight set 0      # turn off keyboard backlight
    on-resume   = brightnessctl -r $kbd_backlight             # restore keyboard backlight.
}

# Lock session after 5 mins idle
listener {
    timeout     = $min5                                    
    on-timeout  = loginctl lock-session     # lock screen
}

# Turn off display after 10 mins idle
listener {
    timeout     = $min10                                                                         
    on-timeout  = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                         # screen off when timeout has passed
    on-resume   = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r      # screen on when activity is detected after timeout has fired.
}

# turn on
listener {
    timeout     = $min20                                 # 30min
    on-timeout  = systemctl suspend      # suspend pc
}
