#    _                      _            _
#   | |__  _   _ _ __  _ __| | ___   ___| | __
#   | `_ \| | | | `_ \| `__| |/ _ \ / __| |/ /
#   | | | | |_| | |_) | |  | | ( ) | (__|   <
#   |_| |_|\__, | `__/|_|  |_|\___/ \___|_|\_\
#          |___/|_| 
#

# PALETTE
# #161641, #313172, #4848A8,   #8686B6,   #BCBCCD
#  22,22,65, 49,49,114, 72,72,168, 134,134,182, 188,188,205
$color5 = 188,188,205
$color4 = 134,134,182
$color3 = 72,72,168
$color2 = 49,49,114
$color1 = 22,22,65

# #1A1100, #332200, #483000, #895F0B, #C48C1C
$color55 = 196,140,28
$color44 = 137,95,11
$color33 = 72,48,0
$color22 = 51,34,0
$color11 = 26,17,0

$colorErr = 255,0,0




general {
    ignore_empty_input = true
}

background{
    monitor = # if empty will be displayed on all monitors
    path = $HOME/Pictures/Wallpaper/Liquid1.png
}

input-field{
    monitor = # if empty will be displayed on all monitors
    
    size = 230, 50
    position = 0, -500

    font_color = rgba($color5,1.0)

    outline_thickness = 3
    outer_color = rgba($color5,1.0)
    inner_color = rgba($color4,0.7)
    rounding = -1
    
    fail_text = 
    placeholder_text = Password
    fade_on_empty = false


    check_color = rgba(0,0,0,0.0)
    fail_color = rgba($colorErr,1.0)
}

#Date
label{
    monitor =
    text = cmd[update:100] date +%a\ %d\ %b
    color = rgba($color5, 1.0)
    font_size = 30
    font_family = JetBrainsMono Nerd Font Propo
    position = 0,280
}

#Heure
label{
    monitor = 
    text = cmd[update:1000] echo "$TIME"
    color = rgba($color5, 1.0)
    font_size = 100
    font_family = JetBrainsMono Nerd Font Propo
    position = 0,200
}

label{
    monti
}